# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7847c75bc4a96f7e7e3a5934b523af6da6322b74f9ab1304f40316971be5d6a197e7ca042a664e2d32da110d0054c5363c3110eddc037a35ff40fe721057833

test:
  secret_key_base: 1adb7f0168a4b6a281426df371cc3ded9a0e07a9e0cebbd615141982ccbfcdfa62ae806a9fbdca483c6687bf2c351f30ca75b1b50d9b451fb1f5edc3866ea2ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
